name: Deploy dev stage

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLIENTID: ${{ secrets.GOOGLE_CLIENTID }}
      GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
      CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
      CLOUD_API_SECRET: ${{ secrets.CLOUD_API_SECRET }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      EC2_HOST: ${{ secrets.EC2_HOST }}	
      EC2_KEY: ${{ secrets.EC2_KEY }}

    steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm' 
    - name: clean cache
      run: npm cache clean --force
    - name: install aws
      run: npm install -g aws
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Decode SSH and set permissions
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_KEY }}" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host *" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
    - name: Create env file
      run: |
        echo "${{ secrets.MONGO_URI }}" >> .env
        echo "${{ secrets.GOOGLE_CLIENTID }}" >> .env	
        echo "${{ secrets.GOOGLE_SECRET }}" >> .env	
        echo "${{ secrets.CLOUD_NAME }}" >> .env	
        echo "${{ secrets.CLOUD_API_KEY }}" >> .env	
        echo "${{ secrets.CLOUD_API_SECRET }}" >> .env	
        # echo "${{ secrets.GH_TOKEN }}" >> .env
    - name: Copy env file
      run: scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no .env ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/blog-some
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
        sudo apt-get update
        sudo apt-get install -y nodejs git npm
        cd blog-some
        git pull origin main
        npm install
        npm run start
    - name: thank you
      run: echo "Deployed successfully😁😁"
      